-- 모든 사람의 정보 조회
SELECT * FROM CUSTOMER;

-- 광역시에 거주 중인 사람들의 정보 조회
SELECT * 
FROM CUSTOMER 
WHERE ADDRESS LIKE '%광역시%';

-- 이름이 2자인 사람들의 정보 조회
SELECT * 
FROM CUSTOMER
WHERE LENGTH(NAME) = 2;

-- 이름, 생년월일, 나이 정보 조회
-- EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM BIRTHDATE) + 1
SELECT NAME, BIRTHDATE, CEIL(MONTHS_BETWEEN(SYSDATE, BIRTHDATE)/12) + 1||'세' "나이"
FROM CUSTOMER
ORDER BY "나이";

-- 나이가 30대인 사람들의 정보 조회
SELECT * 
FROM CUSTOMER 
WHERE CEIL(MONTHS_BETWEEN(SYSDATE, BIRTHDATE)/12)+1 BETWEEN 30 AND 39;

